
spring:
  application:
      name: lovebuy-product #自己在注册中心的名称
server:
  port: 8002
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lovebuy_user
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:cn/lemonsports/mapper/*Mapper.xml
  type-aliases-package: cn.lemonsports.domain,cn.lemonsports.query
